### ISSUE TITLE
Server language support (flags)

### ISSUE THREAD

**Issue by marky291** [marky291/ragnaranks#29]
Listings should be able to use a language flag to represent their server.

<img width="373" alt="Screenshot 2019-05-23 at 12 44 42" src="https://user-images.githubusercontent.com/5384515/58250192-bc39a800-7d58-11e9-95d8-d7af91197912.png">

**Comment by MitsuneBewbs** [comment]
What if we do it by Language spoken? Since servers are only hosted in so many places... Usually just broadly Europe/Asia/USA.
https://www.fluentin3months.com/most-spoken-languages/

**Comment by MitsuneBewbs** [comment]
Personally I feel like the list should be catered to what we _know_ is the common player languages used on RO servers. From experience I feel like we have tons of Brazilian, Pinay, and Indo that play RO. So that's **Portuguese, Tagalog, and Hindustani**.
In Europe/Canada it's _French, German, and Dutch_ languages that I've seen but I know there are more languages used in Europe. Americans just speak _English_ but I know that player base isn't as big as it used to be. _Spanish_ countries don't have a ton of varied language, they're really only separated in their accent and slangs. Spain would be one of the only Spanish speaking countries that has major difference in language. I dunno about the _Russians and Chinese_ playing a ton of RO but I imagine they exist lol.
English
Portuguese
Tagalog
Hindustani
Spanish
Malay
Russian
French
Mandarin

**Comment by marky291** [comment]
perfect :D

**Comment by marky291** [comment]
Requires flag graphics
